volumes:
  mongo_data:
    external: true
  mongodb-log:
    driver: local
    name: mongo-log
  weaviate_data:
    external: true
    name: weaviate_data

networks:
  traefik-proxy:
    external: true
    name: traefik

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    container_name: mongodb
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.mongo.rule=Host(`spock-mongo.meza.gg`)
      - traefik.http.routers.mongo.tls=true
      - traefik.http.routers.mongo.entrypoints=mongodb
      - traefik.http.routers.mongo.tls.certresolver=myresolver
      - com.centurylinklabs.watchtower=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - traefik-proxy
    volumes:
      - mongo_data:/data/db/
      - mongodb-log:/var/log/mongodb/

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.mongo-express.rule=Host(`spock-mongo.meza.gg`)
      - traefik.http.routers.mongo-express.tls=true
      - traefik.http.routers.mongo-express.entrypoints=web,websecure
      - traefik.http.routers.mongo-express.tls.certresolver=myresolver
      - com.centurylinklabs.watchtower=true
      - com.centurylinklabs.watchtower.enable=true
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'spock-mongo.meza.gg'
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - 8081:8081
    networks:
      - traefik-proxy


  weaviate:
    labels:
      - traefik.enable=true
      - traefik.http.routers.weaviate.rule=Host(`weaviate.meza.gg`)
      - traefik.http.routers.weaviate.tls=true
      - traefik.http.routers.weaviate.entrypoints=weaviate
      - traefik.http.routers.weaviate.tls.certresolver=myresolver
      - com.centurylinklabs.watchtower=true
      - com.centurylinklabs.watchtower.enable=true
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.29.0
    ports:
      - 8080:8080
    networks:
      - traefik-proxy
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      ENABLE_MODULES: 'text2vec-ollama'
      TEXT2VEC_OLLAMA_ENDPOINT: "http://ollama.meza.gg:11434"
