volumes:
  mongo_data:
    external: true
  mongodb-log:
    driver: local
    name: mongo-log

networks:
  mongodb_network:
    driver: bridge
    name: mongo-network
  traefik-proxy:
    external: true
    name: traefik

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    container_name: mongodb
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.mongo.rule=Host(`spock-mongodb.meza.gg`)
      - traefik.http.routers.mongo.tls=true
      - traefik.http.routers.mongo.entrypoints=mongodb
      - traefik.http.routers.mongo.tls.certresolver=myresolver
      - traefik.http.middlewares.mongo.headers.SSLRedirect=true
      - traefik.http.middlewares.mongo.headers.STSSeconds=315360000
      - traefik.http.middlewares.mongo.headers.browserXSSFilter=true
      - traefik.http.middlewares.mongo.headers.contentTypeNosniff=true
      - traefik.http.middlewares.mongo.headers.forceSTSHeader=true
      - traefik.http.middlewares.mongo.headers.SSLHost=meza.gg
      - traefik.http.middlewares.mongo.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.mongo.headers.STSPreload=true
      - traefik.http.routers.mongo.middlewares=mongo@docker
      - com.centurylinklabs.watchtower=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - traefik-proxy
      - mongodb_network
    volumes:
      - mongo_data:/data/db/
      - mongodb-log:/var/log/mongodb/

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.mongo.rule=Host(`spock-mongodb.meza.gg`)
      - traefik.http.routers.mongo.tls=true
      - traefik.http.routers.mongo.entrypoints=web,websecure
      - traefik.http.routers.mongo.tls.certresolver=myresolver
      - traefik.http.middlewares.mongo.headers.SSLRedirect=true
      - traefik.http.middlewares.mongo.headers.STSSeconds=315360000
      - traefik.http.middlewares.mongo.headers.browserXSSFilter=true
      - traefik.http.middlewares.mongo.headers.contentTypeNosniff=true
      - traefik.http.middlewares.mongo.headers.forceSTSHeader=true
      - traefik.http.middlewares.mongo.headers.SSLHost=meza.gg
      - traefik.http.middlewares.mongo.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.mongo.headers.STSPreload=true
      - traefik.http.routers.mongo.middlewares=mongo@docker
      - com.centurylinklabs.watchtower=true
      - com.centurylinklabs.watchtower.enable=true
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
    ports:
      - 8081:8081
    networks:
      - traefik-proxy
      - mongodb_network
    depends_on:
      - mongodb
