networks:
  traefik-proxy:
    external: true
    name: traefik

volumes:
  n8n_data:
    external: true
  webui_data:
    external: true

services:
  webui:
    container_name: webui
    restart: unless-stopped
    image: ghcr.io/open-webui/open-webui:main
    labels:
      - traefik.enable=true
      - traefik.http.routers.webui.rule=Host(`ai.meza.gg`)
      - traefik.http.routers.webui.tls=true
      - traefik.http.routers.webui.entrypoints=web,websecure
      - traefik.http.routers.webui.tls.certresolver=myresolver
      - traefik.http.middlewares.webui.headers.SSLRedirect=true
      - traefik.http.middlewares.webui.headers.STSSeconds=315360000
      - traefik.http.middlewares.webui.headers.browserXSSFilter=true
      - traefik.http.middlewares.webui.headers.contentTypeNosniff=true
      - traefik.http.middlewares.webui.headers.forceSTSHeader=true
      - traefik.http.middlewares.webui.headers.SSLHost=meza.gg
      - traefik.http.middlewares.webui.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.webui.headers.STSPreload=true
      - traefik.http.routers.webui.middlewares=n8n@docker
      - com.centurylinklabs.watchtower=true
      - com.centurylinklabs.watchtower.enable=true
    expose:
      - 8080
    volumes:
      - webui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama.meza.gg:11434
      - WEBUI_AUTH=False
    networks:
      - traefik-proxy

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8n.meza.gg`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=myresolver
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=meza.gg
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
      - com.centurylinklabs.watchtower=true
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - N8N_HOST=n8n.meza.gg
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.meza.gg/
      - GENERIC_TIMEZONE=Europe/London
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - traefik-proxy
