name: Build and Push

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    strategy:
        matrix:
            target: [ "radarr", "sonarr", "sabnzbd", "gitea", "adguard" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push for normal versions
        uses: docker/build-push-action@v3
        with:
          context: .
          target: ${{ matrix.target }}
          push: true
          no-cache: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/homelab:${{ matrix.target }}
