name: Build and Push

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    strategy:
        matrix:
            target: [ "radarr", "sonarr", "sabnzbd", "gitea", "adguard", "registry", "gitea-mirror" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/homelab
          # generate Docker tags based on the following events/attributes
          tags: |
            typ=raw,value=${{ matrix.target }}
            typ=raw,value=${{ matrix.target }},suffix=-latest
            type=sha,prefix=${{ matrix.target }}-
          labels: |
            com.centurylinklabs.watchtower.enable="true"
      - name: Build and push for normal versions
        uses: docker/build-push-action@v3
        with:
          context: .
          target: ${{ matrix.target }}
          push: ${{ github.ref == 'refs/heads/main' }}
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
